### ISSUE TITLE
Lord British Help Messages

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#23] opened 2020-11-06 18:06 UTC
Weirdly, the first time I talked to Lord British, he responded to the HELP keyword with the message about fetching stones from dungeons. Usually he starts with stick by the towns and get people to join you...

**Comment by cambragol** [comment] 2020-11-06 18:16
That is odd.  

Are you an avatar?

**Comment by cambragol** [comment] 2020-11-06 18:17
I didn't change this area prior to being told to fetch stones. I think something is up with your save game.  

Did you start a new game, or use an old save?

**Comment by MrKnitster** [comment] 2020-11-06 18:19
Nope; started a brand new game. No prior saved games. And definitely not an avatar! Not even a single virtue raised to avatar level yet.

**Comment by cambragol** [comment] 2020-11-06 18:29
no runes? More than 1000 moves?

**Comment by MrKnitster** [comment] 2020-11-06 18:30
2 runes, 4000 moves. What are the triggers for LB? moves and items?

**Comment by cambragol** [comment] 2020-11-06 18:31
There are a bunch, but first is moves, then Party Members (you have more than one?) then runes, then karma.

**Comment by cambragol** [comment] 2020-11-06 18:34
This could be a bug in original Ultima IV Dos

**Comment by cambragol** [comment] 2020-11-06 18:35
Can you attach your save files to this issue?

**Comment by MrKnitster** [comment] 2020-11-06 18:37
Of course! Which save files, incidentally? There appear to be three folders with save files: all items, no items, and dragon.

**Comment by cambragol** [comment] 2020-11-06 18:39
Cool. The save files outside of those. Party.sav, Outmonts.sav, monsters.sav and items.sav. Just zip and attach them.

**Comment by MrKnitster** [comment] 2020-11-06 18:42
Hopefully worked. Files attached.
[saves.zip](https://github.com/cambragol/advent-of-the-trinity/files/5502935/saves.zip)

**Comment by cambragol** [comment] 2020-11-06 18:44
Got it. Thanks. Checking into this now.

**Comment by cambragol** [comment] 2020-11-06 18:51
It looks like this is default behaviour in DOS Ultima IV. So it is an original bug. As you know, he should be telling us to visit the Seer Hawkwind, but it is skipping over that part. 

I took your files and just plugged them straight into Ultima IV dos (vanilla). 

Perhaps this should be fixed.

Hm.

**Comment by cambragol** [comment] 2020-11-07 02:14
I am investigating the default behavior in Apple II version. I believe I have it fixed, and working properly, but just want to make sure. 
If this is a bug, it is a huge bug for the DOS version as it skips over the advice to visit Hawkwind and seek elevation in the eight virtues, practically the main quest of the game!

**Comment by cambragol** [comment] 2020-11-07 02:39
Okay, checked default Apple II. ToTT now matches it. So the original DOS had a bug here.

However, fixing this has pushed the size of Avatar.exe into the unstable realm. Not good. Need to cull a byte or two.

**Comment by cambragol** [comment] 2020-11-07 04:14
bytes culled, safely I hope.

So fixed.

**Comment by cambragol** [comment] 2020-11-07 09:32
This could use a checking. When you have more than 1000 moves, at least one companion, and at least one rune, and no avatarhoods, asking Lord British for help should give this response: "Visit the Seer Hawkwind often and use his wisdom to help thee prove thy virtue."

After getting one avatarhood, he will switch to the following when asked for help: "Go ye now into the depths of the dungeons. Therein recover the 8 colored stones from the altar pedestals in the halls of the dungeons."

**Comment by cambragol** [comment] 2020-11-07 09:32
Of course, wait for the next Beta build

**Comment by cambragol** [comment] 2021-02-09 11:10
This still needs to be confirmed. Should be working, but a second confirmation would be good.

**Comment by MrKnitster** [comment] 2021-02-09 14:58
I'm pretty late in the game, so I am ready for the abyss. I'm getting the help message to deal with the crypts first, which seems totally appropriate.

Are you looking for somebody to go back and restart to track the help messages?

**Comment by cambragol** [comment] 2021-02-09 21:44
No, carry on with the play through by all means. After that this could be looked at.

The Crypt message comes right before the Abyss message, so that sounds correct.

**Comment by MrKnitster** [comment] 2021-02-10 20:01
Crypts done. LB now gives the Abyss message, right on schedule.

**Comment by cambragol** [comment] 2021-02-11 01:24
Yes!

**Comment by cambragol** [comment] 2021-02-12 06:13
Make sure to take a screenshot of the final screens. There should be a subtle difference.

**Comment by cambragol** [comment] 2021-04-30 06:49
This was fixed and tested to closing.

**Closed by cambragol** 2021-04-30 06:49 UTC
Labels: bug, feedback
