### ISSUE TITLE
Active Player - Sleepers never wake up

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#66] opened 2020-11-23 09:52 UTC
This is pretty minor but if I have an active player in a dungeon room and one guy is asleep then they will never wake up.

I think this is cuz they never get a turn so they never have a wake up check.

**Comment by cambragol** [comment] 2020-11-23 10:37
That sounds buggy. I better check that. Active player/sleep interactions are complex.

Did they wake up, after combat? I am not sure if this can be fixed easily...no turn means no chance to wake up...

**Comment by Fenyx4** [comment] 2020-11-23 11:11
I ended up hitting 0 and then they woke up.

Hrm, I'll see if I can recreate it and have the other characters leave and I'll see what happens.

**Comment by cambragol** [comment] 2020-11-23 11:22
If someone leaves and a sleeper is left alone, the active player will revert to them, so they'll get a turn, and should wake up. I tested that case, I'm fairly sure. But please do check it.

**Comment by cambragol** [comment] 2020-11-23 23:44
Also, setting the active player to a sleeping player, just defaults to the next available, awake player. This is how it should work, though a little message such as DISABLED would have been nice. No room now. Nopers.

**Comment by cambragol** [comment] 2020-11-23 23:48
Though, I do have a message set if the player is dead. INVALID. A small conditional check here could make a better message...but...NO room. Dang. Might have to cut a small feature soon to make room for needed fixes.

**Comment by cambragol** [comment] 2020-11-24 05:43
I found a small bug in the Active Player while looking into improving the feedback for slept characters.

When selecting a number for a party member who is not actually in the party YET, the name of the player is given, then said to be INVALID. This should not reveal a party member name who is not a member yet.

I have fixed this now, though slept characters still lack precise feedback on their state.

**Comment by cambragol** [comment] 2020-11-24 06:06
Okay, I think I have the smaller issues here all solved. You will get a DISABLED message when trying to set a slept or dead player to the activer player, and an INVALID message when trying to set to a player not in the party yet (and no name called for the un-joined party member)

However, the original issue stands, in that slept player will not get a chance to wake up if active player is on.  I am not sure if I want to tackle this one, as the code cost will certainly be high.

**Comment by Fenyx4** [comment] 2020-11-24 21:53
I did verify that if you have an active player set and the last player in a room is asleep then that person does wake up.

So at least it doesn't put you in a softlock situation.

I haven't written active player stuff yet form the Randomizer. I'll try to get to that soon then maybe I'll know enough to maybe be able to help.

**Comment by cambragol** [comment] 2020-11-24 22:26
A solution is not thaaat hard. Just need to run a check on if anyone is sleeping, then wake them up on a random chance (while still handling whether they are also poisoned, or in a good state).

However, this must be done in zero lines of net code. Gah.

**Comment by cambragol** [comment] 2020-11-24 23:29
I just tested active player with sleeping companions in Ultima 5 several times, and the sleepers never awoke!

This may be the default behaviour in Ultima 5. Will check some more, but if that is the case, I am not so worried about it. 
Just don't use Active player in those situations?

**Comment by cambragol** [comment] 2020-11-24 23:33
Okay. 100% confirmed. Ultima 5(DOS) Active Player does not wake sleeping characters. Their turn is skipped and they stay asleep until Active player is off, or the current Active player dies/leaves, whereupon the next available player takes a turn.

Soo.....No problem.

**Comment by cambragol** [comment] 2020-11-24 23:37
Also, Ultima 5 does not distinguish between INVALID and slept(disabled) characters like I have. Which means....I could go back to just using INVALID, and save a whole line of code!

I'll keep that in reserve and DISABLED messages can stay for now.

**Comment by Fenyx4** [comment] 2020-11-25 07:09
I wrote my active player code. It isn't fully integrated into the Randomizer but it works as a standalone right now.

https://github.com/Fenyx4/U4DosRandomizer/commit/6af290759d0237c18ac10cf22d129595d4f7c89b

I think it behaves like yours except it allows inactive players to wake up and eat food. I think I like this way better so even though it doesn't match Ultima 5 I think I'll stick with it.
Oh and if someone tries to set an active character that isn't in the party yet it just falls through to "Bad Command" instead. That saves me some lines of code but as that isn't as much of a concern for me I might switch it to how Ultima 5/Threat of Trinity behaves.

I solved the inactive players not waking up by just putting the food eating outside the active player check so it shouldn't take up any more lines of code. 

Dunno if my way of writing it would save you some lines of code but feel free to use anything you can from it if you want to!

P.S. I thought of a way to decrease lines of code more while writing this;
https://github.com/Fenyx4/U4DosRandomizer/commit/4bc70a27128970aa7b7a2181b8a2f94f10ffa286

Although I think this one has slight flaw. If the active player leaves the combat then it takes a full round then it has to loop entirely around once before advancing the active player.

**Comment by cambragol** [comment] 2020-11-25 10:44
I checked out that code. Looks very concise! A different approach than mine, and maybe cleaner/simpler. Have you tested this in game? Because I found lots of finicky stuff with Gra_11 that was needed to make things work right.(issues especially with the highlighting of the Active pc's name.) I am not seeing those issues in your code. 

I will look into incorporating now, as if I could fit in and save space, having a better function than U5 doesn't hurt!

Thanks!

**Comment by Fenyx4** [comment] 2020-11-25 16:58
I did test it in game (and had to fix quite a few bugs before I got it working 😭) but I wasn't paying very close attention to to character highlighting. I will load it up soon and take another look.

**Comment by Fenyx4** [comment] 2020-11-25 17:43
Tested it out. Looks like character highlighting is working correctly.

**Comment by cambragol** [comment] 2020-11-25 22:27
Well, that is good then. I had those bugs too! I still think yours is cleaner than mine, and maybe a bit shorter. Not sure though...
Also, my code benefits from having the next player pop up after an Active player leaves the combat, which yours does not. But mine lacks the sleep check...Not sure which is better there...

Maybe we should just let the other Beta players chime in with their experience. For me, I never heard complaints about the U5 active player, and mine matches that, so perhaps it is enough. Still...

**Comment by Fenyx4** [comment] 2020-11-25 22:49
Yeah, mine has to loop through once before popping up the next player as active. 

Hrm, I will poke at it tonight. I should be able to fix that in my first version without adding any additional code.

**Comment by cambragol** [comment] 2020-11-26 06:30
I have got sleep awake working with my original code. Just testing it now to see if any issues.

**Comment by cambragol** [comment] 2020-11-26 11:53
ooooooo! I just unified my 'Awake' code and maybe saved 3 or 4 lines of code, AND, still have awaking from sleep during Active Player! Yippee!

**Comment by cambragol** [comment] 2020-11-26 13:27
Well, it seem to be working A-okay, and I saved about 8 lines of code. Sweeet. Will include in the next beta.

**Comment by Fenyx4** [comment] 2020-11-26 16:02
Sorry didn't get to it last night and my idea didn't change anything.

Yay 8 lines of code! That is a very appropriate number.

**Comment by cambragol** [comment] 2020-12-02 02:01
This is fixed now, so please watch out for/report on it.

**Comment by cambragol** [comment] 2020-12-09 22:36
Closing this as it seems to be fixed, no further issues.

**Closed by cambragol** 2020-12-09 22:36 UTC
Labels: bug
