### ISSUE TITLE
Dungeon Room Bug

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#181] opened 2021-02-12 15:17 UTC
Ran into a funky bug on L3 of the Abyss. I think there's a trigger that makes monsters appear in this initially empty room, but instead a bunch of caves appeared:

<img width="671" alt="Screen Shot 2021-02-12 at 10 16 48 AM" src="https://user-images.githubusercontent.com/74002028/107786198-8fdb7180-6d1b-11eb-9a32-7b5cdd917c88.png">

**Comment by cambragol** [comment] 2021-02-12 15:22
Okay, this is an easy fix. It is part of what I had to do to add in new tiles. 

I'll have a fix in a few minutes.

**Comment by cambragol** [comment] 2021-02-12 15:27
Wait, so eight caves appeared? There were none initially?

**Comment by cambragol** [comment] 2021-02-12 15:33
Looks like there may be a couple of rooms with this issue.

**Comment by cambragol** [comment] 2021-02-12 15:49
This should fix all instances of caves: they will be back to Daemons. However, the abyss is weird..not 100% this is over.

[ABYSS.DNG.zip](https://github.com/cambragol/advent-of-the-trinity/files/5972853/ABYSS.DNG.zip)

**Comment by cambragol** [comment] 2021-02-12 16:03
Okay...I tested this, and this may also be another default bug! The caves were Trinity, but in default, and trinity, the daemons that appear are frozen. They do not animate.

**Comment by cambragol** [comment] 2021-02-12 16:06
Yep. 100% default u4 bug. The daemons are frozen in all instances where they are created by a trigger.

**Comment by MrKnitster** [comment] 2021-02-12 17:06
Huh. I'll have to check the C64 version.

**Comment by cambragol** [comment] 2021-02-13 01:30
I am going to take a stab at this one, but it may be tricky. Gotta fix it without adding code, otherwise we'll have to assume the intention was to scare the avatar with some statues of daemons.

**Comment by cambragol** [comment] 2021-02-13 06:03
Well, I have it mostly fixed, but it is just too much code. To keep this fix, several small features would have to be cut.

Maybe Fenyx4 can come up with a better solution in U4Randomizer?

**Comment by cambragol** [comment] 2021-02-13 06:30
My cheapo solution for this will be to change the dungeon rooms so the daemons are standing there from the beginning, and do not appear from a trigger.

These 4 places are the only ones in the whole game where a trigger spawns a creature.

**Comment by Fenyx4** [comment] 2021-02-13 13:39
Have we been able to verify if it works in any other version?

**Comment by cambragol** [comment] 2021-02-13 13:53
I don't have an Abyss ready crew in Apple II. I'd have to work to get to that, so unconfirmed in Apple II. Unless we view a play through...

**Comment by cambragol** [comment] 2021-02-13 13:55
Okay, just confirmed in an apple II playthrough. Does not work in Apple II version either. Daemons are statues.

**Comment by cambragol** [comment] 2021-02-13 13:56
https://youtu.be/b0XqwyM7ISs?t=13252

**Comment by Fenyx4** [comment] 2021-02-15 06:29
I also verified it isn't fixed in the SMS version. So seems likely it doesn't work in any version.

Aaaand I fixed it. :)

https://github.com/Fenyx4/U4DosRandomizer/commit/f965f48518a66b56540a49ef9f2b36d7fd5e8ffc

This is a first pass. I'm guessing it adds way too much code for you. I'm going to try to do another pass sometime this week that will cut down on the amount of code.

**Comment by cambragol** [comment] 2021-02-15 07:00
Very Nice.

However, when I saw the amount of code I just clutched my heart, stumbled backward and crashed through a window, falling into the street below. ;)

**Comment by cambragol** [comment] 2021-02-15 10:18
I think the only way to fit something like this in trinity would be to combine general 'initialization' of monsters in an entered room, with monsters created/generated by a trigger. That leaves some potential for keeping the overall code the same. I haven't looked into it too much, but it looks like there would need to be a good chunk of refactoring to achieve something like this.

Currently I would need the solution to be a net -2 lines of code!

**Comment by Fenyx4** [comment] 2021-02-17 01:47
Sadly I don't have it down to -2 lines of code.
I'm not sure exactly how you are counting lines but I'm seeing this as taking up 2 more bytes than pre-daemon trigger fix.
https://github.com/Fenyx4/U4DosRandomizer/compare/master..e96491880252db61364aac06f770cf6a997b726a

(2 bytes might equate to one line of code. Not sure.)

Even if you don't roll this fix into TotT you might be able to use some of my changes to save space for other things;

Only grab the variable from the array once save me 3 bytes
https://github.com/Fenyx4/U4DosRandomizer/commit/e96491880252db61364aac06f770cf6a997b726a

Changing the for loop so you don't need to loc_A << 2 as often
https://github.com/Fenyx4/U4DosRandomizer/commit/fe12cd5d5deda2bf129ca2e5987ff6a3ddf1a478

But your gains may not be as good since you have less code without the daemon fix.

**Comment by cambragol** [comment] 2021-02-17 07:18
I'm just loosely calling things by 'lines' of code, as the quirks haver never let me pin it down to bytes precisly. Though 'lines' are very imprecise as well of course.

I am going to take a look at this, as your fix looks better than mine was before I dropped it. I currently combing through the code (again) looking for places to consolidate or combine code, as I need a tiny bit of space to finish things up right. I really hope I can include a fix for this, but it might not be possible. I'll at the least try to work in those space saving bits you noted above though. Every little bit helps. 

I am currently looking at cutting out the 'dfree' code from the u4_dos.asm and other places, as it seems to be barely used, and may not matter in these modern emulators. It could save me a nice chunk of code.

**Comment by cambragol** [comment] 2021-02-17 08:18
I just tried to roll this in and it was sooooo close. 3 lines of code according to my system. So, maybe I can come back at the very end, and squeeze this in, if nothing else prevents it. 

So I will leave this open and pending for now. 

Nice work and thanks on the code. Much better than I could have managed.

**Comment by cambragol** [comment] 2021-02-17 12:30
Compilers are quirky. I tried using code in the second link up there to save a few bytes, and it actually adds 14bytes!

**Closed** 2022-03-29 12:33 UTC
Labels: bug, wontfix
