### ISSUE TITLE
Balron Frequency

### ISSUE THREAD

**Issue by norgio** [cambragol/advent-of-the-trinity#73] opened 2020-11-25 02:40 UTC
This may be by design, but the frequency at which Balrons appear in the overworld seems disproportionately high.  The likelihood that they will appear - I think they're typically generating in hilly terrain? - is causing for more party wipes than I have ever experienced in the game.  Getting to a stage where negating magic is a possibility comes later and in the early game and in early levels running into them so frequently seems out of balance.  Later stages and at higher levels would make more sense in my estimation.

**Comment by cambragol** [comment] 2020-11-25 03:24
This is discussed extensively here: #10 

Short answer: by design, but still open to adjustments.

**Comment by cambragol** [comment] 2020-11-25 05:22
Also, to clarify a little more, the design is expecting that the player avoids mountains and forested areas until they are ready to venture in. Definitely read through #10, because we have touched on this alot, though nothing firmly decided. Looking for overall input regarding the new mob/spawning system.

**Comment by MrKnitster** [comment] 2020-11-27 13:22
Yeah, they are killing me. I'll check out the new beta and see how it is

**Comment by cambragol** [comment] 2021-05-02 00:54
This is fixed with Beta 13 (or earlier). Balrons appear from the get-go, but not that frequently.

**Closed by cambragol** 2021-05-02 00:54 UTC
Labels: feedback
