### ISSUE TITLE
Hostile Guards in LB Castle

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#279] opened 2021-09-29 22:24 UTC
Bizarre new bug. The guards in LB's castle have turned hostile for no reason. I just entered and they immediately pursued and attacked me. I had not interacted with anyone yet. I tried quitting and reloading; same result. I went next door to Britain, and guards were normal. So far this has only happened in LB's castle. I cannot get them to stop being hostile. I've never seen this before.

**Comment by MrKnitster** [comment] 2021-09-29 22:27
This is strange. Currently, I am only an avatar in Valor. I decided to flee from every guard fight in LBC, and fled from about 10. It did not affect Valor (I did not lose an eighth). I then visited Hawkwind, and I was actually ready for elevation in Honor. All of my other virtues seemed not to have taken a hit.

**Comment by MrKnitster** [comment] 2021-09-29 22:40
Leaving and re-entering does not reset them either

**Comment by cambragol** [comment] 2021-09-29 22:42
Whoa.
Hmm..

New game? Or is this a carry over from a previous Beta?

This can be reset by entering a dungeon I believe.
However, the question is how did they get set off...

**Comment by cambragol** [comment] 2021-09-29 22:44
Where had you gone before entering the castle? A dungeon or a shrine perhaps?

**Comment by MrKnitster** [comment] 2021-09-29 22:45
I did just come out of a dungeon (Wrong) after which I sealed it. Bizarre. This is a new game I started in this beta, and I am about 25000 moves in. What a strange toggle. I'll try entering a dungeon to see if it resets

**Comment by cambragol** [comment] 2021-09-29 22:46
I added this 'feature' a little while back. 

The feature is persistent hostile guards. They stay hostile if you commit a crime in a town.

But they shouldn't become hostile for no reason.

**Comment by cambragol** [comment] 2021-09-29 22:47
Actually, it is a new 'alter guard' code, which also effects guards hostility if they 'see' you steal a treasure.

**Comment by MrKnitster** [comment] 2021-09-29 22:48
This is very strange. As I said, they were hostile immediately upon entry, before I had a chance to do anything. And no guards in any other town are hostile.

**Comment by cambragol** [comment] 2021-09-29 22:51
I think I can see the issue.

I utilized a dungeon only variable to deal with this. But looking at the code, there could be a case where the direction you were facing when you left a dungeon activates the alert in certain locations. I will dig into and fix this tonight.

For now, I am pretty certain that entering a dungeon will reset this.

**Comment by MrKnitster** [comment] 2021-09-29 22:54
Thanks. I'll let you know. Strange that fleeing the guards did not affect virtues...

**Comment by MrKnitster** [comment] 2021-09-29 23:03
Worked as expected. Thank you! Incidentally, I had previously sealed a dungeon. When I went back, it was unsealed. What could have caused this?

**Comment by cambragol** [comment] 2021-09-29 23:30
Yikes.

That is another bug. Better punch that one in.

**Comment by cambragol** [comment] 2021-09-30 10:33
Do you know which dungeon you came out of before heading to Castle Britannia (and being attacked)?

**Comment by cambragol** [comment] 2021-09-30 10:38
Okay, I reproduced the bug. Caused by facing south when leaving a dungeon. So I will need to set the party direction to zero when leaving, to prevent any hostility in towns.

Or...I may need to remove this 'feature' and restore to default in order to free up space to fix the reopening dungeon bug.

**Comment by cambragol** [comment] 2021-09-30 10:46
Fixed in 14.0

**Comment by MrKnitster** [comment] 2021-09-30 11:53
So far it's happened with Wrong and Shame. I don't know if it happened with Deceit or Destard. Definitely did not happen with Despise.

**Comment by cambragol** [comment] 2021-09-30 12:12
It will happen with any dungeon if you leave while facing in the south direction. It doesn't actually matter which one. No worries, as I have this fixed now.

Nice catch on this one though!!

**Comment by cambragol** [comment] 2021-09-30 22:31
This fleeing from guards without losing valor is strange...though it must be because you didn't initiate the combat, and you fled from a nominally 'good' creature, which should not incur a valor loss.

So maybe not strange, just default behavior. Just weird because the battles were initiated because of the other bug. So I don't need to dig into this (unless it showed up for something else, but I doubt that)

**Comment by cambragol** [comment] 2022-03-12 12:38
I tested this and it seems to be working. Visiting a dungeon will cause 'triggered' towns to no longer be triggered.

**Closed by cambragol** 2022-03-12 12:38 UTC
Labels: bug, fixed in 14.0

**Comment by Fenyx4** [comment] 2022-03-12 15:12
> This fleeing from guards without losing valor is strange...though it must be because you didn't initiate the combat, and you fled from a nominally 'good' creature, which should not incur a valor loss.
> 
> So maybe not strange, just default behavior. Just weird because the battles were initiated because of the other bug. So I don't need to dig into this (unless it showed up for something else, but I doubt that)

Newest Speedrun strategy is actually to trigger combat in Castle Britannia and then run from all the guards.

Since they are considered innocent creatures running from them gains compassion so it is a faster method than giving to the beggar... And clears the path to the rune of spirituality. Avatar is not so virtuous in the speedruns. 😔

**Comment by cambragol** [comment] 2022-03-12 16:06
That is hilarious. I guess the ends justify the means?!

**Comment by cambragol** [comment] 2022-03-12 16:07
Oh, I don't think that will work in TotT though...(goes and tests)
