### ISSUE TITLE
Ship Attack (not what you think)

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#178] opened 2021-02-11 21:02 UTC
What in the sweet fancy abyss is this?

<img width="1376" alt="Screen Shot 2021-02-11 at 3 59 27 PM" src="https://user-images.githubusercontent.com/74002028/107698281-4db22180-6c82-11eb-877c-22bb78f78c0a.png">

I am in the pirate bay in the Isle of the Avatar. I attacked and defeated a ship of pirates. And then was attacked by a ship, which led to the screen above. You can see that the monsters (ships) are just called ENEMY. Serious weirdness going on. But kinda fun...

I'll finish the battle if I can and see what happens.

**Comment by MrKnitster** [comment] 2021-02-11 21:04
Also, the ships don't move. Which means, unless I use a mass-damage spell like Tremor, I cannot even kill them because they won't come into range. I obviously killed the ones I could reach, but cannot get into line of fire with several.

**Comment by cambragol** [comment] 2021-02-11 23:26
Hm.

Jeez. Well, I have seen this exact bug reported for Ultima IV before, but I can't remember where or when. (Maybe the GOG forums...) I will have to assume it is a Trinity bug for now though.

**Comment by cambragol** [comment] 2021-02-11 23:34
I was able to reproduce this on my third attack from ships in the abyss. I have never seen this from any pirate ship ever, only here at the Abyss entrance. So there must be something different about the ships generated there.

**Comment by cambragol** [comment] 2021-02-11 23:35
I also silently lost 2 avatarhoods. This is bad.

**Comment by cambragol** [comment] 2021-02-11 23:40
I checked in default U4 and I got the same bug by the third ship attack. So this is a previously underreported default U4 bug.

**Comment by cambragol** [comment] 2021-02-11 23:45
I was able to reproduce this multiple times in default U4. Hm. I am surprised this hasn't been reported more. Did DOS players even finish the game!?

**Comment by cambragol** [comment] 2021-02-12 00:11
Okay, I may have fixed this. Seems like the pirate ship generating code may have been making one more ship than the ai could handle, resulting in an 'out of range' NPC, which creates a 'phantom' (in default, 'enemy' in Trinity)

I have tested multiple times at the Abyss and cannot generate the phantom ship scenario any more. Previously I could reproduce 1 out of every 2 forays into the Abyss Bay.

**Comment by Fenyx4** [comment] 2021-02-12 05:03
I have run into that bug in the original game! I had completely forgotten about it. Nice catch.

Would this be a hard fix for me to incorporate into the Randomizer?

**Comment by cambragol** [comment] 2021-02-12 05:09
Easy.

This is what I changed:

si = 6 was a 7 in the original code. I reduced this to 6. So far it is working. Not 100% sure why, as this was my very first stab at a solution, but I have tested about 10 sorties into the Abyss bay with no phantom encounters.

/*spawn pirate ships*/
Spawn_Pirates()
{
	register int si;

	for(si = 6; si >= 0; si --) {
		D_8742._npc._x[si] = D_08EC[si];
		D_8742._npc._y[si] = D_08F4[si];
		D_8742._npc._tile[si] = TIL_Pirate_Ship_West_80;
		D_8742._npc._gtile[si] = D_08FC[si];
	}
}

**Comment by cambragol** [comment] 2021-02-12 06:02
Incidentally, while pursuing this bug I found TWO more bugs in default DOS u4 and apple II!

In Apple II, a certain condition triggers the failure of the Skull to work anymore. It just has no effect thereafter (not sure the cause yet)

In DOS the skull disappears if you use it in the Abyss!

**Comment by MrKnitster** [comment] 2021-02-12 13:12
In C64, the skull also disappears if you use it (cast it into) the abyss.

I have never run across the ship bug in C64. Didn't really play DOS.

**Comment by cambragol** [comment] 2021-02-12 13:20
I mean, the skull disappears if you use it when you are 'inside' the abyss. Maybe not a bug, but not exactly expected behaviour as well.

The ship bug never showed up in Apple II either. I tested it today, and it never happened in my memory either.

**Closed** 2021-02-13 01:32 UTC
Labels: bug
